language: perl

perl:
  - '5.16'
  - '5.14'
  - '5.18'

sudo: false

before_install:
  - git clone git://github.com/travis-perl/helpers.git ~/travis-perl-helper
  - source ~/travis-perl-helper/init
  - build-perl
  - perl -V

install:
  - cpanm -v --notest Net::Whois::Raw
  - cpanm -v --notest Net::Whois::Norid
  - cpanm -v --notest Devel::Cover
  - cpanm -v --notest Devel::Cover::Report::Coveralls
  - cpanm -v --notest --installdeps .

env: COVERAGE=1

before_script:
  - coverage-setup

script:
  - perl Build.PL
  - ./Build
  - prove -bv t

after_success:
  - coverage-report
