language: perl
perl:
  - "5.14"
  - "5.16"
  - "5.18"
env: COVERAGE=1
sudo: false
before_install:
  - cpanm -n Devel::Cover::Report::Coveralls
  - cpanm -n Net::Ping::External
script:
  perl Build.PL && ./Build build && cover -test -report coveralls
