language: perl
perl:
  - "5.14"
  - "5.16"
  - "5.18"
matrix:
  include:
    - perl: 5.14
      env: COVERAGE=1
    - perl: 5.16
      env: COVERAGE=1
    - perl: 5.18
      env: COVERAGE=1
sudo: false
before_install:
  - git clone git://github.com/travis-perl/helpers ~/travis-perl-helpers
  - source ~/travis-perl-helpers/init
  - build-perl
  - perl -V
  - build-dist
  - cd $BUILD_DIR
install:
  - cpan-install Net::Whois::Raw
  - cpan-install Net::Whois::Norid
  - cpan-install Devel::Cover
  - cpan-install Devel::Cover::Report::Coveralls
  - cpan-install Net::Ping::External
  - cpan-install --deps
  - cpan-install --coverage
before_script:
  - coverage-setup
script:
  - prove -lv $(test-dirs)
after_success:
  - coverage-report
