language: perl
script: prove -lr t
install:
  - cpanm -n -q --skip-satisfied --installdeps .
perl:
  - 5.14
before_install:
  cpanm -n Devel::Cover::Report::Coveralls
script:
  perl Build.PL && ./Build build && cover -test -report coveralls
